apiVersion: v1
kind: Service
metadata:
  labels:
    app: retirement-calculator
  name: retirement-svc
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: retirement-calculator
