apiVersion: v1
kind: Pod
metadata:
  name: retirement-pod
  labels:
   zone: prod
   version: v1
spec:
  containers:
  - name: retirement-ctr
    image: neilc89/spa-demo:v1
    ports:
    - containerPort: 8080
