apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value
    app: retirement-calculator
  name: service-name-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 8080
    protocol: TCP
  selector:
    app: retirement-calculator
 #for creating a deployment in kubernetes
 kubectl apply -f spa-deployment.yaml
 #for internal communicating to angualar application
 kubeclt apply -f SPA-service.yaml
 #for access the angular application outside kubernetes
 kubeclt apply -f SPA-load-balancer-service.yaml
